from mongoengine import *


class Planet(Document):
    mass = StringField(required=True)
    volume = StringField(required=True)
    e_radius = StringField(required=True)
    p_radius = StringField(required=False)
    v_mean_radius = StringField(required=False)
    ellipticity = StringField(required=False)
    m_density = StringField(required=False)
    s_gravity = StringField(required=False)
    s_acceleration = StringField(required=False)
    e_velocity = StringField(required=False)
    GM = StringField(required=False)
    b_albedo = StringField(required=False)
    g_albedo = StringField(required=False)
    v_band = StringField(required=False)
    s_irradiance = StringField(required=False)
    black_body = StringField(required=False)
    t_range = StringField(required=False)
    m_inertia = StringField(required=False)
    J2 = StringField(required=False)
    s_axis = StringField(required=False)
    s_o_period = StringField(required=False)
    t_period = StringField(required=False)
    Perihelion = StringField(required=False)
    Aphelion = StringField(required=False)
    Sy_period = StringField(required=False)
    Mean_velocity = StringField(required=False)
    Max_velocity = StringField(required=False)
    Min_velocity = StringField(required=False)
    o_inclination = StringField(required=False)
    o_eccentricity = StringField(required=False)
    s_r_period = StringField(required=False)
    l_o_day = StringField(required=False)
    o_t_o = StringField(required=False)
    i_o_e = StringField(required=False)
